version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    command: >
      sh -c "
          python manage.py sync_cassandra &&
          python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      cassandra:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_HOST=cassandra
      - DB_NAME=tu_keyspace
      - DB_PORT=9042
      - DB_USER=admin  
      - DB_PASSWORD=adminpassword
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    networks:
      - mynetwork

  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - mynetwork
    volumes:
      - cassandra_data:/var/lib/cassandra 
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_START_RPC=true
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  cassandra_data:
